### ISSUE TITLE
MOD 10,30 & 40 Not match

### ISSUE THREAD

**Issue by cheahengsoon** [microsoft/ignite-learning-paths-training-mod#14]
Hi Team,
May You check again the MOD 10,MOD 30 and MOD 40?
Here with the issue I found.

- MOD 10 Migrating Web Applications to Azure - currently link to [MOD10 - Options for Building and Running Your App in the Cloud](https://github.com/microsoft/ignite-learning-paths-training-mod/blob/master/mod10/README.md) ?

- MOD30: Modernizing Your Application with Containers - currently link to [MOD30 - Enhancing Web Applications with Cloud Intelligence](https://github.com/microsoft/ignite-learning-paths-training-mod/blob/master/mod30/README.md) ?

- MOD40: Consolidating Infrastructure with Azure Kubernetes Service - currently link to [MOD40 - Debugging and interacting with production applications ](https://github.com/microsoft/ignite-learning-paths-training-mod/blob/master/mod40/README.md)?

**Comment by FBoucher** [comment]
Got it. Thanks @cheahengsoon I'll fix that.
