### ISSUE TITLE
MOD10: Image Classifier doesn't work on upload

### ISSUE THREAD

**Issue by sjwaight** [microsoft/ignite-learning-paths-training-mod#41]
When attempting to upload a new image the image classifier service endpoint returns a 400 bad request and an error is displayed to the user. 

The backend service logs the following error:

System.DllNotFoundException: Unable to load shared library 'onnxruntime' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libonnxruntime: cannot open shared object file: No such file or directory

**Comment by FBoucher** [comment]
@sjwaight when/why are you trying to upload a new image? Can you provide more context please?

**Comment by sjwaight** [comment]
This error occurs after having provisioned the site on a fresh VM as per instructions and using deploy.sh. I'll go back and grab a fresh copy of the files now everything is merged and re-run to see if this issue goes away with the corrected scripts.

**Comment by FBoucher** [comment]
@jaydestro can you provide more detail here :)

**Comment by jaydestro** [comment]
@anthonychu could u help? Uncertain of where it’s trying to store this

**Comment by anthonychu** [comment]
Not sure if this has ever been tested in the VM deployment. Is the image upload part of the demo script? If not, I would just ignore it.

**Comment by jaydestro** [comment]
there is no portion of mod10 requiring this functionality.  closed.
