### ISSUE TITLE
MOD30: Demo 4 lacks intructions, is using deprecated App Center API.

### ISSUE THREAD

**Issue by sjwaight** [microsoft/ignite-learning-paths-training-mod#49]
Recommending this Demo is removed.

When the Logic App is loaded for the first time it must be connected to Twitter. If the demonstrator does not have a Twitter account handy they will have to go through a complete setup and may not be familiar with this process or have an account they can use.

Secondly, the push notification API for App Center has been deprecated as of 3 Feb, 2020 (see https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/).

**Comment by FBoucher** [comment]
Thank you @sjwaight this is a good suggestion. We will adjust the demos.
